version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "YourStrong@Password123"   # Choose a strong password!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      # Override the connection string to point to the SQL Server container.
      # Note: Use SQL authentication instead of Integrated Security.
      ConnectionStrings__MyDB: "Data Source=db;Initial Catalog=CareSkin;User ID=sa;Password=YourStrong@Password123;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
